"""followers

Revision ID: 13561dd62e87
Revises: 52cdee0a8440
Create Date: 2023-08-08 12:12:26.722540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13561dd62e87'
down_revision = '52cdee0a8440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
