"""remove profile_image column in User model

Revision ID: 446cc07d36cb
Revises: b91a116e0f4f
Create Date: 2023-08-17 13:19:04.187208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446cc07d36cb'
down_revision = 'b91a116e0f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(length=128), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
