"""remove one column

Revision ID: 99b28d859266
Revises: df565bede38d
Create Date: 2023-08-16 11:32:59.218646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b28d859266'
down_revision = 'df565bede38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.VARCHAR(length=140), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
