"""remove mobile field

Revision ID: a1eaf3698627
Revises: f49861c9e860
Create Date: 2023-07-28 15:07:19.134335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1eaf3698627'
down_revision = 'f49861c9e860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
